# From https://stackoverflow.com/a/60881827/701926

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'

target 'ReactTypeScriptSample' do
	#use_frameworks!
  config = use_native_modules!
  use_react_native!(
     :path => config[:reactNativePath],
     # to enable hermes on iOS, change `false` to `true` and then install pods
     # By default, Hermes is disabled on Old Architecture, and enabled on New Architecture.
     # You can enable/disable it manually by replacing `flags[:hermes_enabled]` with `true` or `false`.
     :hermes_enabled => true
   )

  target 'ReactTypeScriptSampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'ReactTypeScriptSample-tvOS' do
  # Pods for ReactTypeScriptSample-tvOS

  target 'ReactTypeScriptSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
