# From https://stackoverflow.com/a/60881827/701926

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'UXCamReactExample' do
  # Adding 'use_frameworks!' creates Cyclic dependency issue with other targets
  # https://github.com/facebook/react-native/issues/31034
	#use_frameworks!
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'UXCamReactExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'UXCamReactExample-tvOS' do
  # Pods for ReactTypeScriptSample-tvOS

  target 'UXCamReactExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
