# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
 
platform :ios, min_ios_version_supported
prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'UXCamReactExample' do
  # Adding 'use_frameworks!' creates Cyclic dependency issue with other targets
  # https://github.com/facebook/react-native/issues/31034
	#use_frameworks!
  
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath],
                    :hermes_enabled => false,
                    )

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'UXCamReactExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
                              installer,
                              config[:reactNativePath],
                              :mac_catalyst_enabled => false,
                              # :ccache_enabled => true
                              )
  end
end

target 'UXCamReactExample-tvOS' do
  # Pods for ReactTypeScriptSample-tvOS

  target 'UXCamReactExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
