export const images: any = {
  creditCard: require('../../assets/credit-card-sample.jpg'),
  bug: require('../../assets/bug/bug.png'),
  plateCheese: require('../../assets/platecheese/plate_cheese.png'),
  risotto: require('../../assets/list/risotto.jpeg'),
  pizza: require('../../assets/list/pizza.jpeg'),
  friedShrimp: require('../../assets/list/friedShrimp.jpeg'),
  iceCream: require('../../assets/list/iceCream.jpeg'),
  onionRings: require('../../assets/list/onionRings.jpeg'),
  cheeseCake: require('../../assets/list/cheeseCake.jpeg'),
  frenchFries: require('../../assets/list/frenchFries.jpeg'),
  burger: require('../../assets/list/burger.jpeg'),
  tick: require('../../assets/common/tick.png'),
  menu: require('../../assets/common/menu.png'),
  stack: require('../../assets/common/stack.png'),
};
