export const palette = {
  white: '#FFFFFF',
  alto: '#dcdcdc',
  black: '#000000',
  background: '#e6e6e6',
  gray: 'gray',
  darkGray: 'darkgray',
  error: '#a90808',
  transparent: 'transparent',
  blue: 'blue',
  skyBlue: '#4287f5',
  customBlue: '#32AAE6',
  green: 'green',
  yellow: 'yellow',
  orange: 'orange',
  pastelPink: '#FFB4B4',
  pastelBlue: '#083cbf',
  pastelGreen: '#98DAAA',
  pastelYellow: '#e9fa02',
  pastelPurple: '#CDBEEB',
  seaSerpent: '#5AC4BD',
};
